#ifndef CPP3_SMARTCALC_V2_CALCULATOR_S21_CONTROLLER_H
#define CPP3_SMARTCALC_V2_CALCULATOR_S21_CONTROLLER_H

#include "../Model/s21_model.h"



#endif  // CPP3_SMARTCALC_V2_CALCULATOR_S21_CONTROLLER_H